apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcms-frontend-app-deployment
  namespace: dev
  labels:
    app.kubernetes.io/name: tcms-frontend-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tcms-frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tcms-frontend-app
    spec:
      # serviceAccountName: deployment-manager-sa
      containers:
      - name: tcms-frontend-container
        image: 677043464437.dkr.ecr.ap-south-1.amazonaws.com/tcms:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: tcms-frontend-app-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: tcms-frontend-app
